"""Handoff functionality for AI Scrum Team.

Provides an endpoint to transfer a conversation from the current agent to a target agent,
persisting the handoff event and invoking the target agent with the conversation context.
"""

import os
from typing import Any, Dict, Optional

from fastapi import APIRouter, HTTPException, Request, status
from pydantic import BaseModel, Field

# Router to be included in the main FastAPI app
router = APIRouter(prefix="/handoff", tags=["handoff"])

# Pydantic model for request validation
class HandoffRequest(BaseModel):
    conversation_id: str = Field(..., description="ID of the conversation to hand off")
    target_agent_id: str = Field(..., description="ID of the target agent that will take over")
    metadata: Optional[Dict[str, Any]] = Field(default_factory=dict, description="Optional extra data")

# Response model (optional, FastAPI will generate schema automatically)
class HandoffResponse(BaseModel):
    status: str = Field(..., example="ok")
    new_conversation_id: str = Field(..., description="ID of the new conversation created for the target agent")
    message: str = Field(..., description="Human readable result message")

# Helper functions – in a real project these would be in separate modules
async def persist_handoff_event(
    conversation_id: str, source_agent_id: str, target_agent_id: str, metadata: Dict[str, Any]
) -> int:
    """Insert a handoff record into the database.

    Returns the primary key of the inserted row.
    """
    # Simple implementation using environment variables for DB connection.
    # The project already uses `psycopg2` in other scripts; we reuse that.
    import psycopg2
    from psycopg2.extras import Json

    conn_str = os.getenv("POSTGRES_URL") or "postgresql://postgres:postgres@localhost:5432/postgres"
    sql = """
        INSERT INTO handoff_log (conversation_id, source_agent_id, target_agent_id, metadata)
        VALUES (%s, %s, %s, %s)
        RETURNING id;
    """
    async def _run():
        with psycopg2.connect(conn_str) as conn:
            with conn.cursor() as cur:
                cur.execute(sql, (conversation_id, source_agent_id, target_agent_id, Json(metadata)))
                row_id = cur.fetchone()[0]
                conn.commit()
                return row_id
    # psycopg2 is blocking; for simplicity we run it in a thread pool.
    import asyncio
    return await asyncio.get_event_loop().run_in_executor(None, _run)

async def fetch_conversation_context(conversation_id: str) -> Dict[str, Any]:
    """Retrieve the stored messages for a conversation.

    This is a stub – in a full implementation it would query the appropriate tables.
    For now we return a dummy context to keep the endpoint functional for tests.
    """
    # Placeholder: return empty context
    return {"messages": []}

async def invoke_target_agent(target_agent_id: str, context: Dict[str, Any]) -> str:
    """Call the ai-agent service to activate the target agent.

    Returns the new conversation ID generated by the target agent.
    """
    import httpx
    ai_agent_url = os.getenv("AI_AGENT_URL", "http://ai-agent:8000")
    endpoint = f"{ai_agent_url}/agents/{target_agent_id}/activate"
    try:
        async with httpx.AsyncClient() as client:
            resp = await client.post(endpoint, json={"context": context})
            resp.raise_for_status()
            data = resp.json()
            return data.get("conversation_id", f"conv-{target_agent_id}-fallback")
    except Exception as exc:
        raise HTTPException(status_code=502, detail=f"Failed to invoke target agent: {exc}")

@router.post("/", response_model=HandoffResponse, status_code=status.HTTP_200_OK)
async def handoff(request: Request, payload: HandoffRequest):
    """Endpoint to hand off a conversation to another agent.

    Steps:
    1. Persist handoff event.
    2. Retrieve current conversation context.
    3. Call target agent with that context.
    4. Return the new conversation identifier.
    """
    # In a real system the source agent would be derived from auth token or request header.
    source_agent_id = request.headers.get("X-Source-Agent", "unknown")

    # Persist the handoff event
    try:
        await persist_handoff_event(
            conversation_id=payload.conversation_id,
            source_agent_id=source_agent_id,
            target_agent_id=payload.target_agent_id,
            metadata=payload.metadata,
        )
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Failed to record handoff: {exc}")

    # Fetch conversation context (stubbed)
    context = await fetch_conversation_context(payload.conversation_id)

    # Invoke the target agent
    new_conv_id = await invoke_target_agent(payload.target_agent_id, context)

    return HandoffResponse(
        status="ok",
        new_conversation_id=new_conv_id,
        message=f"Conversation handed off to {payload.target_agent_id}",
    )
