spring:
  application:
    name: scheduler-service
  r2dbc:
    url: r2dbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_DATABASE:cloud_master}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:widowmaker}
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    com.app: DEBUG
