import { Category } from '../../../types/apps/Types'
import type { ProductType } from '../../../types/apps/productType'

export const MOCK_CATEGORIES: Category[] = [
  { id: 'ALL', name: 'All Items' },
  { id: 'BURGER', name: 'Burgers' },
  { id: 'PIZZA', name: 'Pizza' },
  { id: 'DRINK', name: 'Drinks' }
]

const now = new Date().toISOString()

export const MOCK_PRODUCTS: ProductType[] = [
  {
    image: undefined,
    id: 1,
    tenantId: 1,
    productName: 'Classic Cheeseburger',
    description: '',
    productType: '0', // Producto simple
    price: 8.99,
    salePrice: null,
    sku: 'BOOK001',
    barcode: 'BOOK001',
    manageStock: true,
    inventoryStatus: 'IN_STOCK',
    allowBackorders: 'NO',
    inventoryQty: 50,
    soldIndividually: false,
    weight: null,
    dimensions: '',
    upsellProducts: '',
    crossSellProducts: '',
    status: 'ACTIVE',
    brand: '',
    model: '',
    categoryIds: [], // aquí luego mapeas a IDs reales
    imageIds: [],
    createdAt: now,
    updatedAt: now
  },
  {
    image: undefined,
    id: 2,
    tenantId: 1,
    productName: 'Double Bacon BBQ',
    description: '',
    productType: '0',
    price: 12.5,
    salePrice: null,
    sku: 'PEN002',
    barcode: 'PEN002',
    manageStock: true,
    inventoryStatus: 'IN_STOCK',
    allowBackorders: 'NO',
    inventoryQty: 30,
    soldIndividually: false,
    weight: null,
    dimensions: '',
    upsellProducts: '',
    crossSellProducts: '',
    status: 'ACTIVE',
    brand: '',
    model: '',
    categoryIds: [],
    imageIds: [],
    createdAt: now,
    updatedAt: now
  },
  {
    image: undefined,
    id: 3,
    tenantId: 1,
    productName: 'Margherita Pizza',
    description: '',
    productType: '0',
    price: 14.0,
    salePrice: null,
    sku: 'PENCIL003',
    barcode: 'PENCIL003',
    manageStock: true,
    inventoryStatus: 'IN_STOCK',
    allowBackorders: 'NO',
    inventoryQty: 20,
    soldIndividually: false,
    weight: null,
    dimensions: '',
    upsellProducts: '',
    crossSellProducts: '',
    status: 'ACTIVE',
    brand: '',
    model: '',
    categoryIds: [],
    imageIds: [],
    createdAt: now,
    updatedAt: now
  },
  {
    image: undefined,
    id: 4,
    tenantId: 1,
    productName: 'Pepperoni Feast',
    description: '',
    productType: '0',
    price: 16.5,
    salePrice: null,
    sku: 'BOARD004',
    barcode: 'BOARD004',
    manageStock: true,
    inventoryStatus: 'IN_STOCK',
    allowBackorders: 'NO',
    inventoryQty: 25,
    soldIndividually: false,
    weight: null,
    dimensions: '',
    upsellProducts: '',
    crossSellProducts: '',
    status: 'ACTIVE',
    brand: '',
    model: '',
    categoryIds: [],
    imageIds: [],
    createdAt: now,
    updatedAt: now
  },
  {
    image: undefined,
    id: 5,
    tenantId: 1,
    productName: 'Cola Zero',
    description: '',
    productType: '0',
    price: 2.5,
    salePrice: null,
    sku: 'SKETCH005',
    barcode: 'SKETCH005',
    manageStock: true,
    inventoryStatus: 'IN_STOCK',
    allowBackorders: 'NO',
    inventoryQty: 100,
    soldIndividually: false,
    weight: null,
    dimensions: '',
    upsellProducts: '',
    crossSellProducts: '',
    status: 'ACTIVE',
    brand: '',
    model: '',
    categoryIds: [],
    imageIds: [],
    createdAt: now,
    updatedAt: now
  },
  {
    image: undefined,
    id: 6,
    tenantId: 1,
    productName: 'Lemonade Fresh',
    description: '',
    productType: '0',
    price: 3.5,
    salePrice: null,
    sku: 'BAG006',
    barcode: 'BAG006',
    manageStock: true,
    inventoryStatus: 'IN_STOCK',
    allowBackorders: 'NO',
    inventoryQty: 80,
    soldIndividually: false,
    weight: null,
    dimensions: '',
    upsellProducts: '',
    crossSellProducts: '',
    status: 'ACTIVE',
    brand: '',
    model: '',
    categoryIds: [],
    imageIds: [],
    createdAt: now,
    updatedAt: now
  },
  {
    image: undefined,
    id: 7,
    tenantId: 1,
    productName: 'Chocolate Lava Cake',
    description: '',
    productType: '0',
    price: 6.99,
    salePrice: null,
    sku: 'CAKE007',
    barcode: 'CAKE007',
    manageStock: true,
    inventoryStatus: 'IN_STOCK',
    allowBackorders: 'NO',
    inventoryQty: 15,
    soldIndividually: false,
    weight: null,
    dimensions: '',
    upsellProducts: '',
    crossSellProducts: '',
    status: 'ACTIVE',
    brand: '',
    model: '',
    categoryIds: [],
    imageIds: [],
    createdAt: now,
    updatedAt: now
  },
  {
    image: undefined,
    id: 8,
    tenantId: 1,
    productName: 'Vanilla Bean Shake',
    description: '',
    productType: '0',
    price: 5.5,
    salePrice: null,
    sku: 'SHAKE008',
    barcode: 'SHAKE008',
    manageStock: true,
    inventoryStatus: 'IN_STOCK',
    allowBackorders: 'NO',
    inventoryQty: 40,
    soldIndividually: false,
    weight: null,
    dimensions: '',
    upsellProducts: '',
    crossSellProducts: '',
    status: 'ACTIVE',
    brand: '',
    model: '',
    categoryIds: [],
    imageIds: [],
    createdAt: now,
    updatedAt: now
  }
]
